package comparisonOperator

import com.plf.diary.drools.entity.ComparisonOperatorEntity

rule "rule_comparison_contains"
    when
        ComparisonOperatorEntity(names contains "张三")
    then
        System.out.println("rule_comparison_contains规则触发了");
end

rule "rule_comparison_notcontains"
    when
        ComparisonOperatorEntity(names not contains "张三")
        ComparisonOperatorEntity(list not contains names)
    then
        System.out.println("rule_comparison_notcontains 规则触发了");
end

//测试比较操作符memberOf
rule "rule_comparison_memberOf"
    when
        ComparisonOperatorEntity(names memberOf list)
    then
        System.out.println("rule_comparison_memberOf 规则触发了");
end

//测试比较操作符not memberOf
rule "rule_comparison_not_memberOf"
    when
        ComparisonOperatorEntity(names not memberOf list)
    then
        System.out.println("rule_comparison_not_memberOf 规则触发了");
end

//测试比较操作符matches
rule "rule_comparison_matches"
    when
        ComparisonOperatorEntity(names matches "王.*")
    then
        System.out.println("rule_comparison_matches 规则触发了");
end

//测试比较操作符not matches
rule "rule_comparison_not_matches"
    when
        ComparisonOperatorEntity(names not matches "王.*")
    then
        System.out.println("rule_comparison_not_matches 规则触发了");
end